### ISSUE TITLE
Save as .mp3 in server instead of .webm

### ISSUE THREAD

**Issue by Segouta** [DanielKoomen/WebApp#21]
So you can download full list from server and play on more devices easier.

**Comment by Derkades** [comment]
not sure about this one, mp3 would require transcoding, increasing file size while reducing quality. Maybe there's a more compatible container format that still supports opus?

**Comment by Segouta** [comment]
I understand that point of view, but if I would like to download an entire list from server it would be easy if that is in .mp3 format, right?

**Comment by Derkades** [comment]
It now uses the .ogg file format which is compatible with all media players I am aware of
