### ISSUE TITLE
fast-forward or fast-forward-15 icon? (poll)

### ISSUE THREAD

**Issue by Derkades** [DanielKoomen/WebApp#28]
A) `rewind-15` / `fast-forward-15`
![image](https://user-images.githubusercontent.com/15892014/191086420-426e901a-9c42-4896-b881-3e3b9c1776e5.png)

B) `rewind` / `fast-forward`
![image](https://user-images.githubusercontent.com/15892014/191086577-901e1625-5d39-4a29-af29-0d410692f942.png)

**Comment by DanielKoomen** [comment]
A
