### ISSUE TITLE
EXTREMELY HARD: Music Tags

### ISSUE THREAD

**Issue by Segouta** [DanielKoomen/WebApp#36]
Being able to add tags to music (for example: chill, house, hardstyle, dnb, rock) to be able to switch those on and off.

**Comment by Derkades** [comment]
might not be *that* far off, metadata like genre is already stored in cache. It shouldn't be that hard to make an efficient, dynamic, genre-keyed index

**Comment by Derkades** [comment]
Basic UI implemented in d848a12647e924506bbc84b91c5305c5f36dbd45

**Comment by Segouta** [comment]
Can we make it so that we can make our own tags actually and assign tracks to it? Could be as basic as being able to add tag to currently playing song. That way users can search songs, and add tags to them while they are playing. Maybe the tags could then be an option in the "who's song is playing"-section

**Comment by Derkades** [comment]
the possibility to edit metadata (like artist, album, title, but also tags) can be added in the future
