### ISSUE TITLE
scrolling, and remove from playlist not behaving

### ISSUE THREAD

**Issue by Jeppoer** [DanielKoomen/WebApp#62]
On mobile, swiping the playlist usually focusses on scrolling the entire webpage. Possibly has something to do with the 'remove from playlist' function not working?

**Comment by Derkades** [comment]
Not sure how to improve the queue scrolling experience, the browser decides which element to scroll. Perhaps overlays would work better on mobile?

**Comment by Jeppoer** [comment]
It was working normally before, i have a video explaining what is wrong, i hope it is attached correctly

**Comment by Jeppoer** [comment]
Ok nope it is not, i'll send it on telegram

**Comment by Derkades** [comment]
Added scroll buttons for mobile clients

a6b27776c28a4b692b121de4acdf2d0b5f3c6254
43898c391263210c1a4f494283eb45c3615f834b
