### ISSUE TITLE
Order of Guest Users

### ISSUE THREAD

**Issue by WikeDuivenvoorden** [DanielKoomen/WebApp#66]
(Petty issue) I don't want to be the last guest :(. Ordering the guests by the time they joined i.e. newest guest last... or reverse alphabetical ordering could also solve this.

**Comment by Derkades** [comment]
Soon, playlists will be linked to accounts #60. It will then be possible to display "your own" playlists first

**Comment by Derkades** [comment]
Finally implemented!
